<?xml version="1.0" encoding="utf-16"?>
<LogEntry xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <GlobalName>H.Service.IISHost</GlobalName>
  <LocalName>H.Service.IISHost</LocalName>
  <Content>Message: A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: SQL Network Interfaces, error: 26 - Error Locating Server/Instance Specified).
Exception Type: System.Data.SqlClient.SqlException.
Source: .Net SqlClient Data Provider.
Module Name: C:\Windows\Microsoft.Net\assembly\GAC_32\System.Data\v4.0_4.0.0.0__b77a5c561934e089\System.Data.dll.
Stack Trace:    at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal&amp; connection)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at H.Core.DataAccess.DbHelper.GetOpenConnection(String connectionString, IDbFactory factory, Boolean disposeInnerConnection) in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DbHelper.cs:line 97
   at H.Core.DataAccess.DbHelper.GetOpenConnection(String connectionString, IDbFactory factory) in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DbHelper.cs:line 74
   at H.Core.DataAccess.DbHelper.ExecuteReader(String databaseName, CommandType cmdType, String cmdText, Int32 timeout, DbParameter[] commandParameters) in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DbHelper.cs:line 137
   at H.Core.DataAccess.DataCommand.ExecuteDataReader() in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DataCommand.cs:line 355
   at H.Core.DataAccess.DataCommand.ExecuteEntity[T](Action`2 manualMapper, Boolean propertyNameIgnoreCase, Boolean skipNotExistProperty, Char splitter) in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DataCommand.cs:line 502
   at H.Core.DataAccess.DataCommand.ExecuteEntity[T](Action`2 manualMapper, Boolean propertyNameIgnoreCase, Boolean skipNotExistProperty) in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DataCommand.cs:line 496
   at H.Core.DataAccess.DataCommand.ExecuteEntity[T]() in e:\Desktop\H.Framework_V2\H.Core\H.Core.DataAccess\DataCommand.cs:line 486
   at H.Service.SqlDataAccess.SystemUser.SystemUserDataAccess.Login(SystemUserEntity entity) in e:\Desktop\H.Framework_V2\H.Service\H.Service.Domain\H.Service.SqlDataAccess\SystemUser\SystemUserDataAccess.cs:line 51
   at H.Service.AppService.SystemUserAppService.Login(SystemUserEntity entity) in e:\Desktop\H.Framework_V2\H.Service\H.Service.Domain\H.Service.AppService\SystemUser\SystemUserAppService.cs:line 43
   at H.Service.Rest.SystemUserService.Login(SystemUserEntity entity) in e:\Desktop\H.Framework_V2\H.Service\H.Service.Domain\H.Service.Rest\SystemUser\SystemUserService.cs:line 68
   at SyncInvokeLogin(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet).
</Content>
  <Category>ExceptionLog</Category>
  <ExtendedProperties>
    <ExtendedPropertyData>
      <PropertyName>Method Arguments Type</PropertyName>
      <PropertyValue xsi:type="xsd:string">N/A</PropertyValue>
    </ExtendedPropertyData>
    <ExtendedPropertyData>
      <PropertyName>Method Arguments Value</PropertyName>
      <PropertyValue xsi:type="xsd:string">N/A</PropertyValue>
    </ExtendedPropertyData>
  </ExtendedProperties>
</LogEntry>
数据库连接失败**********************************************************************
rvice\H.Service.Domain\H.Service.SqlDataAccess\SystemUser\SystemUserDataAccess.cs:line 51
   at H.Service.AppService.SystemUserAppService.Login(SystemUserEntity entity) in e:\Desktop\H.Framework_V2\H.Service\H.Service.Domain\H.Service.AppService\SystemUser\SystemUserAppService.cs:line 43
   at H.Service.Rest.SystemUserService.Login(SystemUserEntity entity) in e:\Desktop\H.Framework_V2\H.Service\H.Service.Domain\H.Service.Rest\SystemUser\SystemUserService.cs:line 68
   at SyncInvokeLogin(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]&amp; outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc&amp; rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet).
</Content>
  <Category>ExceptionLog</Category>
  <ExtendedProperties>
    <ExtendedPropertyData>
      <PropertyName>Method Arguments Type</PropertyName>
      <PropertyValue xsi:type="xsd:string">N/A</PropertyValue>
    </ExtendedPropertyData>
    <ExtendedPropertyData>
      <PropertyName>Method Arguments Value</PropertyName>
      <PropertyValue xsi:type="xsd:string">N/A</PropertyValue>
    </ExtendedPropertyData>
  </ExtendedProperties>
</LogEntry>
数据库连接失败**********************************************************************
